<?php

function barcode_array(){

    $barcode_array=[
        // [
        //     'Barcode Type'=>0,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>10,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13,
        //     'position'=>'Department`Code'
        // ],
        // [
        //     'Barcode Type'=>1,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'2',
        //     'Code'=>'6',
        //     'LFCode'=>'',
        //     'Price'=>'4',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>2,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'2',
        //     'Code'=>'5',
        //     'LFCode'=>'',
        //     'Price'=>'5',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>3,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'2',
        //     'Code'=>'4',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>4,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'2',
        //     'Code'=>'3',
        //     'LFCode'=>'',
        //     'Price'=>'7',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>5,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'X.XXX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>6,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>7,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>8,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>9,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>10,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'20(2)',
        //     'Code'=>10,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>11,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'21(2)',
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>4,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>12,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'22(2)',
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>13,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'23(2)',
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>14,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'24(2)',
        //     'Code'=>3,
        //     'LFCode'=>'',
        //     'Price'=>7,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ], 
        // [
        //     'Barcode Type'=>15,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'25(2)',
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'X.XXX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>16,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'26(2)',
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>17,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'27(2)',
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>18,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'28(2)',
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>19,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'29(2)',
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'1',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>20,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'',
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>21,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>7,
        //     'LFCode'=>'',
        //     'Price'=>4,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>22,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>23,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>24,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>7,
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>25,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>7,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'X.XXX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>26,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>7,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XX(4)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>27,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>28,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>29,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>30,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>31,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>32,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>33,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>34,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>35,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>36,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>37,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>38,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>39,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>40,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>41,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>42,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>43,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>44,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>45,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>46,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>0,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>47,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>0,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>48,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>0,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>49,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>0,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>50,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>'',
        //     'Code'=>7,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>51,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>52,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        //  [
        //     'Barcode Type'=>53,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>'',
        //     'Code'=>8,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>54,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>1,
        //     'Code'=>7,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>55,
        //     'Barcode Name'=>'EAN8',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>56,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>57,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>58,
        //     'Barcode Name'=>'EAN13',
        //     'Department'=>'',
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>59,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'',
        //     'Code'=>10,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>60,
        //     'Barcode Name'=>'EAN128-ISBN',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>61,
        //     'Barcode Name'=>'EAN128-ISBN ',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>62,
        //     'Barcode Name'=>'EAN128-1SBN',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>63,
        //     'Barcode Name'=>'EAN128-ISBN',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>64,
        //     'Barcode Name'=>'EAN128-ISBN',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>65,
        //     'Barcode Name'=>'EAN128-ISBN',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>5,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>66,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>5,
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>2,
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>67,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>5,
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>2,
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>68,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>4,
        //     'LFCode'=>5,
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>2,
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>69,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>70,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>71,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>72,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>73,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>74,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>75,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>76,
        //     'Barcode Name'=>'',
        //     'Department'=>'',
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>77,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'27(2)',
        //     'Code'=>'27(2)',
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>5,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>78,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'25(2)',
        //     'Code'=>'25(2)',
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>5,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>79,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>80,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>81,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>82,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>83,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>84,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>85,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>86,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'',
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>87,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>88,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'23(2)+2',
        //     'Code'=>'',
        //     'LFCode'=>'3',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>89,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>'',
        //     'Code'=>'',
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>'',
        //     'length'=>13
        // ],

        // [
        //     'Barcode Type'=>90,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>4,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>91,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>4,
        //     'Weight'=>'XXXX.X(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>92,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>4,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>93,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>1,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>5,
        //     'Weight'=>'',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>94,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>5,
        //     'Unit Price'=>'',
        //     'Weight'=>'XXX.XX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>95,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>4,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>96,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>6,
        //     'LFCode'=>'',
        //     'Price'=>'',
        //     'Unit Price'=>4,
        //     'Weight'=>'XXXXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>97,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>4,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>'',
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        // [
        //     'Barcode Type'=>98,
        //     'Barcode Name'=>'EAN128',
        //     'Department'=>2,
        //     'Code'=>5,
        //     'LFCode'=>'',
        //     'Price'=>6,
        //     'Unit Price'=>5,
        //     'Weight'=>'XX.XXX(5)',
        //     'Batch No'=>'',
        //     'DisCount'=>'',
        //     'checkSum'=>1,
        //     'length'=>13
        // ],
        [
            'Barcode Type'=>101,
            'Barcode Name'=>'EAN13',
            'Department'=>'',
            'Code'=>6,
            'LFCode'=>'',
            'Price'=>'',
            'Unit Price'=>'',
            'Weight'=>6,
            'Batch No'=>'',
            'DisCount'=>'',
            'checkSum'=>1,
            'length'=>13
        ]


        
        
       
    ];

    return $barcode_array;
}

?>