<?php namespace App\Models;
use CodeIgniter\Model;

class CompanySettings extends Model{
  protected $table = 'company_settings';
  protected $allowedFields = ['company_id', 'invoice_prefix', 'sales_prefix', 'sales_order_prefix', 'sales_quotation_prefix', 'sales_return_prefix', 'sales_delivery_prefix', 'purchase_order_prefix', 'purchase_quotation_prefix', 'purchase_return_prefix', 'purchase_delivery_prefix', 'purchase_prefix', 'invoice_auto_archive', 'Invoice_color', 'invoice_footer', 'estimate_prefix', 'estimate_auto_archive', 'estimate_color', 'estimate_footer', 'payment_prefix', 'payment_auto_archive', 'payment_color', 'payment_footer', 'discount_per_item', 'tax_per_item', 'currency', 'timezone', 'month_start', 'month_end', 'keyboard', 'items_kit_show', 'stock_enable', 'invoice_template', 'receipt_template', 'billing_style', 'printer1', 'printer2', 'loc', 'print_thermal', 'show_batch_no', 'show_price', 'show_tax', 'show_discount', 'show_quantity', 'language', 'show_logo', 'show_expiry_date', 'show_due_date', 'show_head', 'invoice_font_color','results_per_page','invoice_header','invoice_signature','invoice_seal','sms_sender','receivers_phone','source_ref','smtp_host','smtp_port','smtp_user','smtp_password','from_name','email_receiver','delivery_days','primary_color','secondary_color','show_entry', 'show_site_visit', 'show_direct_loss', 'show_quotation', 'show_follow_up', 'show_loss', 'show_sales_order', 'show_deliver_note', 'show_delivery', 'show_invoice', 'show_payment_followup', 'show_complete','bank_details','bank_details','invoice_terms','invoice_declaration','upi','merchant_id','content_language','target_country','content_api_key','merchant_currency','show_uom','leave_for_month','carry_forward','payslip_signature','show_hsncode_no','split_tax','copies','preview','width','height','margin1','margin2','margin3','margin4','silent','header','footer','dpi','time_out_per_line','cursor_position','bar_copies','bar_preview','bar_width','bar_height','bar_margin1','bar_margin2','bar_margin3','bar_margin4','bar_silent','bar_header','bar_footer','bar_dpi','bar_time_out_per_line','bar_printer1','bar_printer2','display_price','invoice_qr_code','round_after','taxnumber','tinnumber','make_image','make_image_receipt','pdf_type','show_mrn_number','show_validity','port','baudrate','databits','stopbits','parity','buffersize','weighing_mac','invoice_height','w_device','allow_massanger','feedback','footer_title','description','challan_prefix','grade_system','security_key','enable_payment','api_key','barcode_settings','subunit_devide','body_width','bar_body_width','barcode_height','barcode_width','barcode_fontsize','barcode_marginbottom','round_of_value','fp_device','fp_port','fp_address','allow_receipt_date','hide_deleted','price_for_barcode','border','border-width','bar_padding1','bar_padding2','font_size','margin_top','margin_bot','proforma_invoice_prefix','from_email','pos_focus_element'];


}
