<?php namespace App\Models;
use CodeIgniter\Model;

class InvoiceTaxesVertical extends Model{
  protected $table = 'invoice_taxes_vertical';
  protected $allowedFields = [
    'invoice_id',
    'SGST_9_tax_amount', 
    'CGST_9_tax_amount', 
    'SGST_0_05_tax_amount', 
    'CGST_0_05_tax_amount', 
    'SGST_0_125_tax_amount', 
    'CGST_0_125_tax_amount', 
    'SGST_0_75_tax_amount', 
    'CGST_0_75_tax_amount', 
    'SGST_1_5_tax_amount', 
    'CGST_1_5_tax_amount', 
    'SGST_2_5_tax_amount', 
    'CGST_2_5_tax_amount', 
    'SGST_3_tax_amount', 
    'CGST_3_tax_amount', 
    'SGST_6_tax_amount', 
    'CGST_6_tax_amount', 
    'SGST_6_9_tax_amount', 
    'CGST_6_9_tax_amount', 
    'SGST_7_tax_amount', 
    'CGST_7_tax_amount', 
    'SGST_14_tax_amount', 
    'CGST_14_tax_amount', 
    'IGST_18_tax_amount', 
    'IGST_0_1_tax_amount', 
    'IGST_0_25_tax_amount', 
    'IGST_1_5_tax_amount', 
    'IGST_3_tax_amount', 
    'IGST_5_tax_amount', 
    'IGST_6_tax_amount', 
    'IGST_12_tax_amount', 
    'IGST_13_8_tax_amount', 
    'IGST_14_tax_amount', 
    'IGST_28_tax_amount', 
    'Cess_12_tax_amount', 
    'Cess_60_tax_amount', 
    'VAT_5_tax_amount', 
    'SGST_9_taxable_amount', 
    'CGST_9_taxable_amount', 
    'SGST_0_05_taxable_amount', 
    'CGST_0_05_taxable_amount', 
    'SGST_0_125_taxable_amount', 
    'CGST_0_125_taxable_amount', 
    'SGST_0_75_taxable_amount', 
    'CGST_0_75_taxable_amount', 
    'SGST_1_5_taxable_amount', 
    'CGST_1_5_taxable_amount', 
    'SGST_2_5_taxable_amount', 
    'CGST_2_5_taxable_amount', 
    'SGST_3_taxable_amount', 
    'CGST_3_taxable_amount', 
    'SGST_6_taxable_amount', 
    'CGST_6_taxable_amount', 
    'SGST_6_9_taxable_amount', 
    'CGST_6_9_taxable_amount', 
    'SGST_7_taxable_amount', 
    'CGST_7_taxable_amount', 
    'SGST_14_taxable_amount', 
    'CGST_14_taxable_amount', 
    'IGST_18_taxable_amount', 
    'IGST_0_1_taxable_amount', 
    'IGST_0_25_taxable_amount', 
    'IGST_1_5_taxable_amount', 
    'IGST_3_taxable_amount', 
    'IGST_5_taxable_amount', 
    'IGST_6_taxable_amount', 
    'IGST_12_taxable_amount', 
    'IGST_13_8_taxable_amount', 
    'IGST_14_taxable_amount', 
    'IGST_28_taxable_amount', 
    'Cess_12_taxable_amount', 
    'Cess_60_taxable_amount', 
    'VAT_5_taxable_amount', 
  ];
}



